# Generated by Django 4.2.6 on 2023-12-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpredictions',
            name='probablity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
