# Generated by Django 4.2.6 on 2023-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userpredictions_probablity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpredictions',
            name='disease',
            field=models.CharField(max_length=100),
        ),
    ]
